
services:

  backend:
    build: ./backend
    ports:
    - 5000:5000
    env_file: '.env'
    depends_on:
      database:
        condition: service_healthy


  database:
    build: ./postgres_db
    ports: 
      - 5432:5432
    env_file: '.env'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      retries: 5
      start_period: 30s
      timeout: 10s


  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend